# Generated by Django 4.2.30 on 2026-06-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statitem',
            name='label',
            field=models.CharField(help_text='Description shown below the number', max_length=150),
        ),
        migrations.AlterField(
            model_name='statitem',
            name='number',
            field=models.CharField(help_text='e.g. 100%, 15 min, 90%', max_length=20),
        ),
        migrations.AlterField(
            model_name='usecaseslide',
            name='overlay_text',
            field=models.CharField(default='Record. Edit. Publish.', help_text='Bold text overlaid on the card image area', max_length=120),
        ),
        migrations.AlterField(
            model_name='voicecard',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Upload MP3/WAV. If empty, a simulated animation plays.', null=True, upload_to='voice_audio/'),
        ),
        migrations.AlterField(
            model_name='voicecard',
            name='duration',
            field=models.FloatField(default=4.0, help_text='Simulated duration in seconds (used when no audio file)'),
        ),
        migrations.AlterField(
            model_name='voicecard',
            name='name',
            field=models.CharField(help_text='Voice name shown on the card', max_length=100),
        ),
        migrations.AlterField(
            model_name='voicecard',
            name='script_text',
            field=models.TextField(help_text='Bangla sentence this voice will say'),
        ),
        migrations.AlterField(
            model_name='voicecard',
            name='wave_seed',
            field=models.IntegerField(default=42, help_text='Controls the waveform bar shape (any integer)'),
        ),
    ]
