# Generated by Django 6.0.5 on 2026-06-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_statitem_label_alter_statitem_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='announcement_text',
            field=models.CharField(default='Our Ambassadors use Bangla Speech AI for free. You in?', max_length=250),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cta_subtitle',
            field=models.TextField(default='Join 50,000+ creators using Bangla Speech AI to produce studio-quality audio in minutes'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cta_title',
            field=models.CharField(default='Start creating for free', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_btn_primary',
            field=models.CharField(default='Try now for free', max_length=60),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_btn_secondary',
            field=models.CharField(default='Build with API', max_length=60),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(default='Generate studio-quality audio with Bangla Speech AI. Choose from 1000+ Bangla AI voices and create voiceovers in seconds.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='1000+ realistic Bangla AI voices', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title_highlight',
            field=models.CharField(default='for any mood', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='stats_heading',
            field=models.CharField(default='Rely on TTS technology built for scale', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='voices_heading',
            field=models.CharField(default='Bangla voice clips mapped to real business scenarios', max_length=200),
        ),
    ]
