# Generated by Django 6.0.5 on 2026-06-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sitesettings_announcement_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(blank=True, default='', help_text='Shown in navbar & footer. Leave empty to use the default BSA text.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_black',
            field=models.FileField(blank=True, help_text='Logo for light/white backgrounds. PNG/SVG/WebP recommended.', null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_white',
            field=models.FileField(blank=True, help_text='Logo for dark backgrounds (navbar, footer). PNG/SVG/WebP recommended.', null=True, upload_to='logos/'),
        ),
    ]
