# Generated by Django 6.0.5 on 2026-06-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_demobooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demobooking',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='demobooking',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='demobooking',
            name='speech',
        ),
        migrations.AddField(
            model_name='demobooking',
            name='agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demobooking',
            name='business_context',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='demobooking',
            name='company',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='demobooking',
            name='full_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='demobooking',
            name='monthly_volume',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='demobooking',
            name='use_case',
            field=models.CharField(blank=True, choices=[('podcast', 'Podcast / Content Creation'), ('audiobook', 'Audiobook / E-learning'), ('ivr', 'IVR / Call Center'), ('marketing', 'Marketing / Advertising'), ('training', 'Training / Corporate'), ('app', 'Mobile / Web App'), ('other', 'Other')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Shown as "Or email directly" link on the Book a Demo form', max_length=254),
        ),
    ]
