# Generated by Django 6.0.5 on 2026-06-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_demobooking_redesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.FileField(blank=True, help_text='Browser tab icon. Recommended: 32×32 or 64×64 PNG/ICO/SVG.', null=True, upload_to='logos/'),
        ),
    ]
