# Generated by Django 6.0.5 on 2026-06-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('badge_text', models.CharField(blank=True, default='', help_text="e.g. 'Most Popular'", max_length=50)),
                ('price', models.CharField(help_text="e.g. '$0', '$49', 'Custom'", max_length=20)),
                ('price_period', models.CharField(blank=True, default='per month', max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('features', models.TextField(help_text='One feature per line')),
                ('cta_text', models.CharField(default='Get started', max_length=60)),
                ('cta_url', models.CharField(blank=True, default='#', max_length=200)),
                ('is_featured', models.BooleanField(default=False, help_text='Highlighted card with accent border')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'verbose_name_plural': 'Pricing Plans',
                'ordering': ['order'],
            },
        ),
    ]
